# : Manager [[[

[mgr]
cwd = { fg = "#e5e1e9" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ff72be", bg = "#ff72be" }
marker_cut      = { fg = "#ffd8ed", bg = "#ffd8ed" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#ffade0", bg = "#ffade0" }

# Count
count_copied   = { fg = "#3b002e", bg = "#ffd8ed" }
count_cut      = { fg = "#3b002e", bg = "#ffd8ed" }
count_selected = { fg = "#302176", bg = "#ffade0" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#c9bfff" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "‚ñà", close = "‚ñà" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c9bfff", bold = true, bg = "#141318" }
inactive  = { fg = "#c9c1ea", bg = "#141318" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c9bfff", fg = "#302176", bold = true }
normal_alt  = { bg = "#484551", fg = "#c9c4d3" }

# Select mode
select_main = { bg = "#c9c1ea", fg = "#312c4c", bold = true }
select_alt  = { bg = "#484551", fg = "#c9c4d3" }

# Unset mode
unset_main = { bg = "#ffade0", fg = "#591048", bold = true }
unset_alt  = { bg = "#484551", fg = "#c9c4d3" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "ü≠Å", close = "ü≠†" }
sep_right = { open = "ü≠Å", close = "ü≠†" }

# Permissions
perm_type  = { fg = "#654fc3" }
perm_write = { fg = "#ff14a6" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff3fa6" }
perm_sep   = { fg = "#6c45ff" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c9bfff", bg = "#3a383e" }
progress_error  = { fg = "#ffb4ab", bg = "#3a383e" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a383e" }
cand = { fg = "#c9bfff" }
rest = { fg = "#302176" }
desc = { fg = "#e5e1e9" }
separator = " ‚ñ∂ "
separator_style = { fg = "#e5e1e9" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#ffade0" }
title_warn  = { fg = "#c9bfff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#c9bfff" }
active = { fg = "#ffade0", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#c9bfff" }
value  = { fg = "#e5e1e9" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#c9bfff", bg = "#302176" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#c9bfff" }
title   = {}
hovered = { fg = "#ffd8ed", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e5e1e9" }
run    = { fg = "#e5e1e9" }
footer = { fg = "#312c4c", bg = "#c9c1ea" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e5e1e9" },
    { url = "*/", fg = "#c9bfff" },
]

# : ]]]
