format = """
$username$hostname$directory$git_branch$git_status$rust$nodejs$python$package$time$line_break$character"""

add_newline = true
palette = "colors"

[palettes.colors]
mustard = '#af8700' # example
color1 = '#b6cacb'
color2 = '#213435'
color3 = '#c2c8c7'
color4 = '#1f2020'
color5 = '#213435'
color6 = '#131313'
color7 = '#131313'
color8 = '#b6cacb'
color9 = '#cbc3d7'

[username]
show_always = false
format = "[$user]($style) "
style_user = "bold blue"
style_root = "bold red"

[hostname]
ssh_only = true
format = "on [$hostname]($style) "
style = "bold purple"
trim_at = "."

[directory]
style = "bold blue"
truncation_length = 3
truncation_symbol = "‚Ä¶/"
read_only = " üîí"
home_symbol = "~"

[git_branch]
symbol = "Óú• "
style = "bold purple"

[git_status]
style = "bold yellow"
conflicted = "√ó"
ahead = "‚Üë$count"
behind = "‚Üì$count"
diverged = "‚Üï"
untracked = "?"
stashed = "‚â°"
modified = "!"
staged = "+"
renamed = "¬ª"
deleted = "‚úò"

[rust]
symbol = "Óû® "
style = "bold red"

[nodejs]
symbol = "Óúò "
style = "bold green"

[python]
symbol = "Óàµ "
style = "bold yellow"

[package]
disabled = false
symbol = "üì¶ "

# –í—Ä–µ–º—è (—Å–ø—Ä–∞–≤–∞, —Å–µ—Ä–æ–µ)
[time]
disabled = false
time_format = "%R"  # 24-—á–∞—Å–æ–≤–æ–π —Ñ–æ—Ä–º–∞—Ç
format = "[$time]($style) "
style = "bold dimmed gray"

# –ü—Ä–æ–º–ø—Ç-—Å–∏–º–≤–æ–ª (–º–æ–∂–Ω–æ —Å–¥–µ–ª–∞—Ç—å –∑–≤—ë–∑–¥–æ—á–∫—É –∏–ª–∏ —Ü–µ–ø—å)
[character]
success_symbol = "[‚òÖ](bold blue)"
error_symbol =   "[‚úó](bold red)"
vimcmd_symbol =  "[ÓüÖ](bold green)"

# –†–∞–∑–¥–µ–ª–∏—Ç–µ–ª—å —Å—Ç—Ä–æ–∫
[line_break]
disabled = false
